# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: route-completion-achievement.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n"route-completion-achievement.proto"\xbf\x01\n\x1aRouteCompletionAchievement\x12\x18\n\x10achievement_uuid\x18\x01 \x01(\t\x12\x12\n\nroute_hash\x18\x02 \x01(\x04\x12 \n\x05sport\x18\x03 \x01(\x0e2\x11.AchievementSport\x12\x10\n\x08bonus_xp\x18\x04 \x01(\r\x12\x15\n\rdisplay_title\x18\x05 \x01(\t\x12\x16\n\x0eanalytics_name\x18\x06 \x01(\t\x12\x10\n\x08unlocked\x18\x07 \x01(\x08"b\n-LoadPlayerRouteCompletionAchievementsResponse\x121\n\x0cachievements\x18\x01 \x03(\x0b2\x1b.RouteCompletionAchievement"D\n\'RouteCompletionAchievementUnlockRequest\x12\x19\n\x11achievement_uuids\x18\x01 \x03(\t*\x91\x01\n\x10AchievementSport\x12!\n\x1dACHIEVEMENT_SPORT_UNSPECIFIED\x10\x00\x12\x1d\n\x19ACHIEVEMENT_SPORT_CYCLING\x10\x01\x12\x1d\n\x19ACHIEVEMENT_SPORT_RUNNING\x10\x02\x12\x1c\n\x18ACHIEVEMENT_SPORT_ROWING\x10\x03b\x06proto2')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'route_completion_achievement_pb2', globals())
# @@protoc_insertion_point(module_scope)
