name: pyinstaller

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: '3.14.7'

    - uses: engineerd/configurator@v0.0.10
      with:
        name: "upx.exe"
        url: "https://github.com/upx/upx/releases/download/v5.2.1/upx-5.2.1-win64.zip"
        pathInArchive: "upx-5.2.1-win64/upx.exe"

    - run: pip install -r requirements.txt
    - run: pip install pyinstaller garth==0.6.22.3
    - run: pyinstaller standalone.spec

    - uses: actions/upload-artifact@v7.0.1
      with:
        path: dist/*
